//
// Created by Orzgg on 1/1/2024.
//

#ifndef GGADV_INCLUDE_COMPONENT_SUB_MODULE_APU_APU_ENUM_H_
#define GGADV_INCLUDE_COMPONENT_SUB_MODULE_APU_APU_ENUM_H_

namespace gg_core {
enum {
  FIFO_SIZE = 8 // 32bit * 8 = 32byte
};

enum HOOKED_TIMER {
  TIMER_0 = 0,
  TIMER_1 = 1
};

enum FIFO_NAME {A, B};

enum E_SOUND_CNT_L {
  RIGHT_OUTPUT_LEVEL_BITFIELD_0_2 = 0,
  LEFT_OUTPUT_LEVEL_BITFIELD_4_6 = 4,
  SOUND_1_RIGHT_OUTPUT_BIT = 8,
  SOUND_2_RIGHT_OUTPUT_BIT = 9,
  SOUND_3_RIGHT_OUTPUT_BIT = 10,
  SOUND_4_RIGHT_OUTPUT_BIT = 11,
  SOUND_1_LEFT_OUTPUT_BIT = 12,
  SOUND_2_LEFT_OUTPUT_BIT = 13,
  SOUND_3_LEFT_OUTPUT_BIT = 14,
  SOUND_4_LEFT_OUTPUT_BIT = 15
};

enum E_SOUND_CNT_X {
  SOUND_1_OPERATION_BIT = 0,
  SOUND_2_OPERATION_BIT = 1,
  SOUND_3_OPERATION_BIT = 2,
  SOUND_4_OPERATION_BIT = 3,
  SOUND_ALL_OPERATION_BIT = 4
};

enum E_SOUND_CNT_H {
  OUTPUT_RATIO_SYNTHESIS_BITFIELD = 0,
  OUTPUT_RATIO_FIFO_A_BITFIELD = 2,
  OUTPUT_RATIO_FIFO_B_BITFIELD = 3,
  RIGHT_OUTPUT_FIFO_A_BIT = 8,
  LEFT_OUTPUT_FIFO_A_BIT = 9,
  HOOKED_TIMER_FIFO_A_BIT = 10,
  FIFO_A_RESET_BIT = 11,
  RIGHT_OUTPUT_FIFO_B_BIT = 12,
  LEFT_OUTPUT_FIFO_B_BIT = 13,
  HOOKED_TIMER_FIFO_B_BIT = 14,
  FIFO_B_RESET_BIT = 15
};
} // namespace gg_core

#endif //GGADV_INCLUDE_COMPONENT_SUB_MODULE_APU_APU_ENUM_H_
