#include <array>

namespace gg_core::gg_cpu {
	static void undefined(GbaInstance& instance) {}
	static void and_shtLSL(GbaInstance& instance) {
	    std::cout << "yee" << std::endl ;
	}
	static void and_shtRsLSL(GbaInstance& instance) {}
	static void and_shtLSR(GbaInstance& instance) {}
	static void and_shtRsLSR(GbaInstance& instance) {}
	static void and_shtASR(GbaInstance& instance) {}
	static void and_shtRsASR(GbaInstance& instance) {}
	static void and_shtROR(GbaInstance& instance) {}
	static void and_shtRsROR(GbaInstance& instance) {}
	static void ands_shtLSL(GbaInstance& instance) {}
	static void ands_shtRsLSL(GbaInstance& instance) {}
	static void ands_shtLSR(GbaInstance& instance) {}
	static void ands_shtRsLSR(GbaInstance& instance) {}
	static void ands_shtASR(GbaInstance& instance) {}
	static void ands_shtRsASR(GbaInstance& instance) {}
	static void ands_shtROR(GbaInstance& instance) {}
	static void ands_shtRsROR(GbaInstance& instance) {}
	static void eor_shtLSL(GbaInstance& instance) {}
	static void eor_shtRsLSL(GbaInstance& instance) {}
	static void eor_shtLSR(GbaInstance& instance) {}
	static void eor_shtRsLSR(GbaInstance& instance) {}
	static void eor_shtASR(GbaInstance& instance) {}
	static void eor_shtRsASR(GbaInstance& instance) {}
	static void eor_shtROR(GbaInstance& instance) {}
	static void eor_shtRsROR(GbaInstance& instance) {}
	static void eors_shtLSL(GbaInstance& instance) {}
	static void eors_shtRsLSL(GbaInstance& instance) {}
	static void eors_shtLSR(GbaInstance& instance) {}
	static void eors_shtRsLSR(GbaInstance& instance) {}
	static void eors_shtASR(GbaInstance& instance) {}
	static void eors_shtRsASR(GbaInstance& instance) {}
	static void eors_shtROR(GbaInstance& instance) {}
	static void eors_shtRsROR(GbaInstance& instance) {}
	static void sub_shtLSL(GbaInstance& instance) {}
	static void sub_shtRsLSL(GbaInstance& instance) {}
	static void sub_shtLSR(GbaInstance& instance) {}
	static void sub_shtRsLSR(GbaInstance& instance) {}
	static void sub_shtASR(GbaInstance& instance) {}
	static void sub_shtRsASR(GbaInstance& instance) {}
	static void sub_shtROR(GbaInstance& instance) {}
	static void sub_shtRsROR(GbaInstance& instance) {}
	static void subs_shtLSL(GbaInstance& instance) {}
	static void subs_shtRsLSL(GbaInstance& instance) {}
	static void subs_shtLSR(GbaInstance& instance) {}
	static void subs_shtRsLSR(GbaInstance& instance) {}
	static void subs_shtASR(GbaInstance& instance) {}
	static void subs_shtRsASR(GbaInstance& instance) {}
	static void subs_shtROR(GbaInstance& instance) {}
	static void subs_shtRsROR(GbaInstance& instance) {}
	static void rsb_shtLSL(GbaInstance& instance) {}
	static void rsb_shtRsLSL(GbaInstance& instance) {}
	static void rsb_shtLSR(GbaInstance& instance) {}
	static void rsb_shtRsLSR(GbaInstance& instance) {}
	static void rsb_shtASR(GbaInstance& instance) {}
	static void rsb_shtRsASR(GbaInstance& instance) {}
	static void rsb_shtROR(GbaInstance& instance) {}
	static void rsb_shtRsROR(GbaInstance& instance) {}
	static void rsbs_shtLSL(GbaInstance& instance) {}
	static void rsbs_shtRsLSL(GbaInstance& instance) {}
	static void rsbs_shtLSR(GbaInstance& instance) {}
	static void rsbs_shtRsLSR(GbaInstance& instance) {}
	static void rsbs_shtASR(GbaInstance& instance) {}
	static void rsbs_shtRsASR(GbaInstance& instance) {}
	static void rsbs_shtROR(GbaInstance& instance) {}
	static void rsbs_shtRsROR(GbaInstance& instance) {}
	static void add_shtLSL(GbaInstance& instance) {}
	static void add_shtRsLSL(GbaInstance& instance) {}
	static void add_shtLSR(GbaInstance& instance) {}
	static void add_shtRsLSR(GbaInstance& instance) {}
	static void add_shtASR(GbaInstance& instance) {}
	static void add_shtRsASR(GbaInstance& instance) {}
	static void add_shtROR(GbaInstance& instance) {}
	static void add_shtRsROR(GbaInstance& instance) {}
	static void adds_shtLSL(GbaInstance& instance) {}
	static void adds_shtRsLSL(GbaInstance& instance) {}
	static void adds_shtLSR(GbaInstance& instance) {}
	static void adds_shtRsLSR(GbaInstance& instance) {}
	static void adds_shtASR(GbaInstance& instance) {}
	static void adds_shtRsASR(GbaInstance& instance) {}
	static void adds_shtROR(GbaInstance& instance) {}
	static void adds_shtRsROR(GbaInstance& instance) {}
	static void adc_shtLSL(GbaInstance& instance) {}
	static void adc_shtRsLSL(GbaInstance& instance) {}
	static void adc_shtLSR(GbaInstance& instance) {}
	static void adc_shtRsLSR(GbaInstance& instance) {}
	static void adc_shtASR(GbaInstance& instance) {}
	static void adc_shtRsASR(GbaInstance& instance) {}
	static void adc_shtROR(GbaInstance& instance) {}
	static void adc_shtRsROR(GbaInstance& instance) {}
	static void adcs_shtLSL(GbaInstance& instance) {}
	static void adcs_shtRsLSL(GbaInstance& instance) {}
	static void adcs_shtLSR(GbaInstance& instance) {}
	static void adcs_shtRsLSR(GbaInstance& instance) {}
	static void adcs_shtASR(GbaInstance& instance) {}
	static void adcs_shtRsASR(GbaInstance& instance) {}
	static void adcs_shtROR(GbaInstance& instance) {}
	static void adcs_shtRsROR(GbaInstance& instance) {}
	static void sbc_shtLSL(GbaInstance& instance) {}
	static void sbc_shtRsLSL(GbaInstance& instance) {}
	static void sbc_shtLSR(GbaInstance& instance) {}
	static void sbc_shtRsLSR(GbaInstance& instance) {}
	static void sbc_shtASR(GbaInstance& instance) {}
	static void sbc_shtRsASR(GbaInstance& instance) {}
	static void sbc_shtROR(GbaInstance& instance) {}
	static void sbc_shtRsROR(GbaInstance& instance) {}
	static void sbcs_shtLSL(GbaInstance& instance) {}
	static void sbcs_shtRsLSL(GbaInstance& instance) {}
	static void sbcs_shtLSR(GbaInstance& instance) {}
	static void sbcs_shtRsLSR(GbaInstance& instance) {}
	static void sbcs_shtASR(GbaInstance& instance) {}
	static void sbcs_shtRsASR(GbaInstance& instance) {}
	static void sbcs_shtROR(GbaInstance& instance) {}
	static void sbcs_shtRsROR(GbaInstance& instance) {}
	static void rsc_shtLSL(GbaInstance& instance) {}
	static void rsc_shtRsLSL(GbaInstance& instance) {}
	static void rsc_shtLSR(GbaInstance& instance) {}
	static void rsc_shtRsLSR(GbaInstance& instance) {}
	static void rsc_shtASR(GbaInstance& instance) {}
	static void rsc_shtRsASR(GbaInstance& instance) {}
	static void rsc_shtROR(GbaInstance& instance) {}
	static void rsc_shtRsROR(GbaInstance& instance) {}
	static void rscs_shtLSL(GbaInstance& instance) {}
	static void rscs_shtRsLSL(GbaInstance& instance) {}
	static void rscs_shtLSR(GbaInstance& instance) {}
	static void rscs_shtRsLSR(GbaInstance& instance) {}
	static void rscs_shtASR(GbaInstance& instance) {}
	static void rscs_shtRsASR(GbaInstance& instance) {}
	static void rscs_shtROR(GbaInstance& instance) {}
	static void rscs_shtRsROR(GbaInstance& instance) {}
	static void tsts_shtLSL(GbaInstance& instance) {}
	static void tsts_shtRsLSL(GbaInstance& instance) {}
	static void tsts_shtLSR(GbaInstance& instance) {}
	static void tsts_shtRsLSR(GbaInstance& instance) {}
	static void tsts_shtASR(GbaInstance& instance) {}
	static void tsts_shtRsASR(GbaInstance& instance) {}
	static void tsts_shtROR(GbaInstance& instance) {}
	static void tsts_shtRsROR(GbaInstance& instance) {}
	static void teqs_shtLSL(GbaInstance& instance) {}
	static void teqs_shtRsLSL(GbaInstance& instance) {}
	static void teqs_shtLSR(GbaInstance& instance) {}
	static void teqs_shtRsLSR(GbaInstance& instance) {}
	static void teqs_shtASR(GbaInstance& instance) {}
	static void teqs_shtRsASR(GbaInstance& instance) {}
	static void teqs_shtROR(GbaInstance& instance) {}
	static void teqs_shtRsROR(GbaInstance& instance) {}
	static void cmps_shtLSL(GbaInstance& instance) {}
	static void cmps_shtRsLSL(GbaInstance& instance) {}
	static void cmps_shtLSR(GbaInstance& instance) {}
	static void cmps_shtRsLSR(GbaInstance& instance) {}
	static void cmps_shtASR(GbaInstance& instance) {}
	static void cmps_shtRsASR(GbaInstance& instance) {}
	static void cmps_shtROR(GbaInstance& instance) {}
	static void cmps_shtRsROR(GbaInstance& instance) {}
	static void cmns_shtLSL(GbaInstance& instance) {}
	static void cmns_shtRsLSL(GbaInstance& instance) {}
	static void cmns_shtLSR(GbaInstance& instance) {}
	static void cmns_shtRsLSR(GbaInstance& instance) {}
	static void cmns_shtASR(GbaInstance& instance) {}
	static void cmns_shtRsASR(GbaInstance& instance) {}
	static void cmns_shtROR(GbaInstance& instance) {}
	static void cmns_shtRsROR(GbaInstance& instance) {}
	static void orr_shtLSL(GbaInstance& instance) {}
	static void orr_shtRsLSL(GbaInstance& instance) {}
	static void orr_shtLSR(GbaInstance& instance) {}
	static void orr_shtRsLSR(GbaInstance& instance) {}
	static void orr_shtASR(GbaInstance& instance) {}
	static void orr_shtRsASR(GbaInstance& instance) {}
	static void orr_shtROR(GbaInstance& instance) {}
	static void orr_shtRsROR(GbaInstance& instance) {}
	static void orrs_shtLSL(GbaInstance& instance) {}
	static void orrs_shtRsLSL(GbaInstance& instance) {}
	static void orrs_shtLSR(GbaInstance& instance) {}
	static void orrs_shtRsLSR(GbaInstance& instance) {}
	static void orrs_shtASR(GbaInstance& instance) {}
	static void orrs_shtRsASR(GbaInstance& instance) {}
	static void orrs_shtROR(GbaInstance& instance) {}
	static void orrs_shtRsROR(GbaInstance& instance) {}
	static void mov_shtLSL(GbaInstance& instance) {}
	static void mov_shtRsLSL(GbaInstance& instance) {}
	static void mov_shtLSR(GbaInstance& instance) {}
	static void mov_shtRsLSR(GbaInstance& instance) {}
	static void mov_shtASR(GbaInstance& instance) {}
	static void mov_shtRsASR(GbaInstance& instance) {}
	static void mov_shtROR(GbaInstance& instance) {}
	static void mov_shtRsROR(GbaInstance& instance) {}
	static void movs_shtLSL(GbaInstance& instance) {}
	static void movs_shtRsLSL(GbaInstance& instance) {}
	static void movs_shtLSR(GbaInstance& instance) {}
	static void movs_shtRsLSR(GbaInstance& instance) {}
	static void movs_shtASR(GbaInstance& instance) {}
	static void movs_shtRsASR(GbaInstance& instance) {}
	static void movs_shtROR(GbaInstance& instance) {}
	static void movs_shtRsROR(GbaInstance& instance) {}
	static void bic_shtLSL(GbaInstance& instance) {}
	static void bic_shtRsLSL(GbaInstance& instance) {}
	static void bic_shtLSR(GbaInstance& instance) {}
	static void bic_shtRsLSR(GbaInstance& instance) {}
	static void bic_shtASR(GbaInstance& instance) {}
	static void bic_shtRsASR(GbaInstance& instance) {}
	static void bic_shtROR(GbaInstance& instance) {}
	static void bic_shtRsROR(GbaInstance& instance) {}
	static void bics_shtLSL(GbaInstance& instance) {}
	static void bics_shtRsLSL(GbaInstance& instance) {}
	static void bics_shtLSR(GbaInstance& instance) {}
	static void bics_shtRsLSR(GbaInstance& instance) {}
	static void bics_shtASR(GbaInstance& instance) {}
	static void bics_shtRsASR(GbaInstance& instance) {}
	static void bics_shtROR(GbaInstance& instance) {}
	static void bics_shtRsROR(GbaInstance& instance) {}
	static void mvn_shtLSL(GbaInstance& instance) {}
	static void mvn_shtRsLSL(GbaInstance& instance) {}
	static void mvn_shtLSR(GbaInstance& instance) {}
	static void mvn_shtRsLSR(GbaInstance& instance) {}
	static void mvn_shtASR(GbaInstance& instance) {}
	static void mvn_shtRsASR(GbaInstance& instance) {}
	static void mvn_shtROR(GbaInstance& instance) {}
	static void mvn_shtRsROR(GbaInstance& instance) {}
	static void mvns_shtLSL(GbaInstance& instance) {}
	static void mvns_shtRsLSL(GbaInstance& instance) {}
	static void mvns_shtLSR(GbaInstance& instance) {}
	static void mvns_shtRsLSR(GbaInstance& instance) {}
	static void mvns_shtASR(GbaInstance& instance) {}
	static void mvns_shtRsASR(GbaInstance& instance) {}
	static void mvns_shtROR(GbaInstance& instance) {}
	static void mvns_shtRsROR(GbaInstance& instance) {}
	static void andi(GbaInstance& instance) {}
	static void andsi(GbaInstance& instance) {}
	static void eori(GbaInstance& instance) {}
	static void eorsi(GbaInstance& instance) {}
	static void subi(GbaInstance& instance) {}
	static void subsi(GbaInstance& instance) {}
	static void rsbi(GbaInstance& instance) {}
	static void rsbsi(GbaInstance& instance) {}
	static void addi(GbaInstance& instance) {}
	static void addsi(GbaInstance& instance) {}
	static void adci(GbaInstance& instance) {}
	static void adcsi(GbaInstance& instance) {}
	static void sbci(GbaInstance& instance) {}
	static void sbcsi(GbaInstance& instance) {}
	static void rsci(GbaInstance& instance) {}
	static void rscsi(GbaInstance& instance) {}
	static void tstsi(GbaInstance& instance) {}
	static void teqsi(GbaInstance& instance) {}
	static void cmpsi(GbaInstance& instance) {}
	static void cmnsi(GbaInstance& instance) {}
	static void orri(GbaInstance& instance) {}
	static void orrsi(GbaInstance& instance) {}
	static void movi(GbaInstance& instance) {}
	static void movsi(GbaInstance& instance) {}
	static void bici(GbaInstance& instance) {}
	static void bicsi(GbaInstance& instance) {}
	static void mvni(GbaInstance& instance) {}
	static void mvnsi(GbaInstance& instance) {}
} // gg_core::gg_cpu
