namespace gg_core::gg_cpu {
	static void strh_Rm(GbaInstance& instance) {}
	static void ldrlh_Rm(GbaInstance& instance) {}
	static void ldrls_Rm(GbaInstance& instance) {}
	static void ldrlsh_Rm(GbaInstance& instance) {}
	static void strh_Imm(GbaInstance& instance) {}
	static void ldrlh_Imm(GbaInstance& instance) {}
	static void ldrls_Imm(GbaInstance& instance) {}
	static void ldrlsh_Imm(GbaInstance& instance) {}
	static void struh_Rm(GbaInstance& instance) {}
	static void ldrulh_Rm(GbaInstance& instance) {}
	static void ldruls_Rm(GbaInstance& instance) {}
	static void ldrulsh_Rm(GbaInstance& instance) {}
	static void struh_Imm(GbaInstance& instance) {}
	static void ldrulh_Imm(GbaInstance& instance) {}
	static void ldruls_Imm(GbaInstance& instance) {}
	static void ldrulsh_Imm(GbaInstance& instance) {}
	static void strph_Rm(GbaInstance& instance) {}
	static void ldrplh_Rm(GbaInstance& instance) {}
	static void ldrpls_Rm(GbaInstance& instance) {}
	static void ldrplsh_Rm(GbaInstance& instance) {}
	static void strpwh_Rm(GbaInstance& instance) {}
	static void ldrpwlh_Rm(GbaInstance& instance) {}
	static void ldrpwls_Rm(GbaInstance& instance) {}
	static void ldrpwlsh_Rm(GbaInstance& instance) {}
	static void strph_Imm(GbaInstance& instance) {}
	static void ldrplh_Imm(GbaInstance& instance) {}
	static void ldrpls_Imm(GbaInstance& instance) {}
	static void ldrplsh_Imm(GbaInstance& instance) {}
	static void strpwh_Imm(GbaInstance& instance) {}
	static void ldrpwlh_Imm(GbaInstance& instance) {}
	static void ldrpwls_Imm(GbaInstance& instance) {}
	static void ldrpwlsh_Imm(GbaInstance& instance) {}
	static void strpuh_Rm(GbaInstance& instance) {}
	static void ldrpulh_Rm(GbaInstance& instance) {}
	static void ldrpuls_Rm(GbaInstance& instance) {}
	static void ldrpulsh_Rm(GbaInstance& instance) {}
	static void strpuwh_Rm(GbaInstance& instance) {}
	static void ldrpuwlh_Rm(GbaInstance& instance) {}
	static void ldrpuwls_Rm(GbaInstance& instance) {}
	static void ldrpuwlsh_Rm(GbaInstance& instance) {}
	static void strpuh_Imm(GbaInstance& instance) {}
	static void ldrpulh_Imm(GbaInstance& instance) {}
	static void ldrpuls_Imm(GbaInstance& instance) {}
	static void ldrpulsh_Imm(GbaInstance& instance) {}
	static void strpuwh_Imm(GbaInstance& instance) {}
	static void ldrpuwlh_Imm(GbaInstance& instance) {}
	static void ldrpuwls_Imm(GbaInstance& instance) {}
	static void ldrpuwlsh_Imm(GbaInstance& instance) {}
} // gg_core::gg_cpu
