#include <array>

namespace gg_core::gg_cpu {
	static void strh_RmOffset(GbaInstance& instance) {}
	static void ldrlh_RmOffset(GbaInstance& instance) {}
	static void ldrl(GbaInstance& instance) {}
	static void ldrlsh_RmOffset(GbaInstance& instance) {}
	static void strh_immOffset(GbaInstance& instance) {}
	static void ldrlh_immOffset(GbaInstance& instance) {}
	static void ldrbl(GbaInstance& instance) {}
	static void ldrlsh_immOffset(GbaInstance& instance) {}
	static void struh_RmOffset(GbaInstance& instance) {}
	static void ldrulh_RmOffset(GbaInstance& instance) {}
	static void ldrul(GbaInstance& instance) {}
	static void ldrulsh_RmOffset(GbaInstance& instance) {}
	static void struh_immOffset(GbaInstance& instance) {}
	static void ldrulh_immOffset(GbaInstance& instance) {}
	static void ldrubl(GbaInstance& instance) {}
	static void ldrulsh_immOffset(GbaInstance& instance) {}
	static void strph_RmOffset(GbaInstance& instance) {}
	static void ldrplh_RmOffset(GbaInstance& instance) {}
	static void ldrpl(GbaInstance& instance) {}
	static void ldrplsh_RmOffset(GbaInstance& instance) {}
	static void strpwh_RmOffset(GbaInstance& instance) {}
	static void ldrpwlh_RmOffset(GbaInstance& instance) {}
	static void ldrpwl(GbaInstance& instance) {}
	static void ldrpwlsh_RmOffset(GbaInstance& instance) {}
	static void strph_immOffset(GbaInstance& instance) {}
	static void ldrplh_immOffset(GbaInstance& instance) {}
	static void ldrpbl(GbaInstance& instance) {}
	static void ldrplsh_immOffset(GbaInstance& instance) {}
	static void strpwh_immOffset(GbaInstance& instance) {}
	static void ldrpwlh_immOffset(GbaInstance& instance) {}
	static void ldrpbwl(GbaInstance& instance) {}
	static void ldrpwlsh_immOffset(GbaInstance& instance) {}
	static void strpuh_RmOffset(GbaInstance& instance) {}
	static void ldrpulh_RmOffset(GbaInstance& instance) {}
	static void ldrpul(GbaInstance& instance) {}
	static void ldrpulsh_RmOffset(GbaInstance& instance) {}
	static void strpuwh_RmOffset(GbaInstance& instance) {}
	static void ldrpuwlh_RmOffset(GbaInstance& instance) {}
	static void ldrpuwl(GbaInstance& instance) {}
	static void ldrpuwlsh_RmOffset(GbaInstance& instance) {}
	static void strpuh_immOffset(GbaInstance& instance) {}
	static void ldrpulh_immOffset(GbaInstance& instance) {}
	static void ldrpubl(GbaInstance& instance) {}
	static void ldrpulsh_immOffset(GbaInstance& instance) {}
	static void strpuwh_immOffset(GbaInstance& instance) {}
	static void ldrpuwlh_immOffset(GbaInstance& instance) {}
	static void ldrpubwl(GbaInstance& instance) {}
	static void ldrpuwlsh_immOffset(GbaInstance& instance) {}
	static void str(GbaInstance& instance) {}
	static void strw(GbaInstance& instance) {}
	static void ldrwl(GbaInstance& instance) {}
	static void strb(GbaInstance& instance) {}
	static void strbw(GbaInstance& instance) {}
	static void ldrbwl(GbaInstance& instance) {}
	static void stru(GbaInstance& instance) {}
	static void struw(GbaInstance& instance) {}
	static void ldruwl(GbaInstance& instance) {}
	static void strub(GbaInstance& instance) {}
	static void strubw(GbaInstance& instance) {}
	static void ldrubwl(GbaInstance& instance) {}
	static void strp(GbaInstance& instance) {}
	static void strpw(GbaInstance& instance) {}
	static void strpb(GbaInstance& instance) {}
	static void strpbw(GbaInstance& instance) {}
	static void strpu(GbaInstance& instance) {}
	static void strpuw(GbaInstance& instance) {}
	static void strpub(GbaInstance& instance) {}
	static void strpubw(GbaInstance& instance) {}
	static void stri(GbaInstance& instance) {}
	static void ldril(GbaInstance& instance) {}
	static void striw(GbaInstance& instance) {}
	static void ldriwl(GbaInstance& instance) {}
	static void strib(GbaInstance& instance) {}
	static void ldribl(GbaInstance& instance) {}
	static void stribw(GbaInstance& instance) {}
	static void ldribwl(GbaInstance& instance) {}
	static void striu(GbaInstance& instance) {}
	static void ldriul(GbaInstance& instance) {}
	static void striuw(GbaInstance& instance) {}
	static void ldriuwl(GbaInstance& instance) {}
	static void striub(GbaInstance& instance) {}
	static void ldriubl(GbaInstance& instance) {}
	static void striubw(GbaInstance& instance) {}
	static void ldriubwl(GbaInstance& instance) {}
	static void strip(GbaInstance& instance) {}
	static void ldripl(GbaInstance& instance) {}
	static void stripw(GbaInstance& instance) {}
	static void ldripwl(GbaInstance& instance) {}
	static void stripb(GbaInstance& instance) {}
	static void ldripbl(GbaInstance& instance) {}
	static void stripbw(GbaInstance& instance) {}
	static void ldripbwl(GbaInstance& instance) {}
	static void stripu(GbaInstance& instance) {}
	static void ldripul(GbaInstance& instance) {}
	static void stripuw(GbaInstance& instance) {}
	static void ldripuwl(GbaInstance& instance) {}
	static void stripub(GbaInstance& instance) {}
	static void ldripubl(GbaInstance& instance) {}
	static void stripubw(GbaInstance& instance) {}
	static void ldripubwl(GbaInstance& instance) {}
} // gg_core::gg_cpu
