namespace gg_core::gg_cpu {
	static void str(GbaInstance& instance) {}
	static void ldrl_ImmLSL(GbaInstance& instance) {}
	static void ldrl_ImmLSR(GbaInstance& instance) {}
	static void ldrl_ImmASR(GbaInstance& instance) {}
	static void ldrl_ImmROR(GbaInstance& instance) {}
	static void strw(GbaInstance& instance) {}
	static void ldrwl_ImmLSL(GbaInstance& instance) {}
	static void ldrwl_ImmLSR(GbaInstance& instance) {}
	static void ldrwl_ImmASR(GbaInstance& instance) {}
	static void ldrwl_ImmROR(GbaInstance& instance) {}
	static void strb(GbaInstance& instance) {}
	static void ldrbl_ImmLSL(GbaInstance& instance) {}
	static void ldrbl_ImmLSR(GbaInstance& instance) {}
	static void ldrbl_ImmASR(GbaInstance& instance) {}
	static void ldrbl_ImmROR(GbaInstance& instance) {}
	static void strbw(GbaInstance& instance) {}
	static void ldrbwl_ImmLSL(GbaInstance& instance) {}
	static void ldrbwl_ImmLSR(GbaInstance& instance) {}
	static void ldrbwl_ImmASR(GbaInstance& instance) {}
	static void ldrbwl_ImmROR(GbaInstance& instance) {}
	static void stru(GbaInstance& instance) {}
	static void ldrul_ImmLSL(GbaInstance& instance) {}
	static void ldrul_ImmLSR(GbaInstance& instance) {}
	static void ldrul_ImmASR(GbaInstance& instance) {}
	static void ldrul_ImmROR(GbaInstance& instance) {}
	static void struw(GbaInstance& instance) {}
	static void ldruwl_ImmLSL(GbaInstance& instance) {}
	static void ldruwl_ImmLSR(GbaInstance& instance) {}
	static void ldruwl_ImmASR(GbaInstance& instance) {}
	static void ldruwl_ImmROR(GbaInstance& instance) {}
	static void strub(GbaInstance& instance) {}
	static void ldrubl_ImmLSL(GbaInstance& instance) {}
	static void ldrubl_ImmLSR(GbaInstance& instance) {}
	static void ldrubl_ImmASR(GbaInstance& instance) {}
	static void ldrubl_ImmROR(GbaInstance& instance) {}
	static void strubw(GbaInstance& instance) {}
	static void ldrubwl_ImmLSL(GbaInstance& instance) {}
	static void ldrubwl_ImmLSR(GbaInstance& instance) {}
	static void ldrubwl_ImmASR(GbaInstance& instance) {}
	static void ldrubwl_ImmROR(GbaInstance& instance) {}
	static void strp(GbaInstance& instance) {}
	static void ldrpl_ImmLSL(GbaInstance& instance) {}
	static void ldrpl_ImmLSR(GbaInstance& instance) {}
	static void ldrpl_ImmASR(GbaInstance& instance) {}
	static void ldrpl_ImmROR(GbaInstance& instance) {}
	static void strpw(GbaInstance& instance) {}
	static void ldrpwl_ImmLSL(GbaInstance& instance) {}
	static void ldrpwl_ImmLSR(GbaInstance& instance) {}
	static void ldrpwl_ImmASR(GbaInstance& instance) {}
	static void ldrpwl_ImmROR(GbaInstance& instance) {}
	static void strpb(GbaInstance& instance) {}
	static void ldrpbl_ImmLSL(GbaInstance& instance) {}
	static void ldrpbl_ImmLSR(GbaInstance& instance) {}
	static void ldrpbl_ImmASR(GbaInstance& instance) {}
	static void ldrpbl_ImmROR(GbaInstance& instance) {}
	static void strpbw(GbaInstance& instance) {}
	static void ldrpbwl_ImmLSL(GbaInstance& instance) {}
	static void ldrpbwl_ImmLSR(GbaInstance& instance) {}
	static void ldrpbwl_ImmASR(GbaInstance& instance) {}
	static void ldrpbwl_ImmROR(GbaInstance& instance) {}
	static void strpu(GbaInstance& instance) {}
	static void ldrpul_ImmLSL(GbaInstance& instance) {}
	static void ldrpul_ImmLSR(GbaInstance& instance) {}
	static void ldrpul_ImmASR(GbaInstance& instance) {}
	static void ldrpul_ImmROR(GbaInstance& instance) {}
	static void strpuw(GbaInstance& instance) {}
	static void ldrpuwl_ImmLSL(GbaInstance& instance) {}
	static void ldrpuwl_ImmLSR(GbaInstance& instance) {}
	static void ldrpuwl_ImmASR(GbaInstance& instance) {}
	static void ldrpuwl_ImmROR(GbaInstance& instance) {}
	static void strpub(GbaInstance& instance) {}
	static void ldrpubl_ImmLSL(GbaInstance& instance) {}
	static void ldrpubl_ImmLSR(GbaInstance& instance) {}
	static void ldrpubl_ImmASR(GbaInstance& instance) {}
	static void ldrpubl_ImmROR(GbaInstance& instance) {}
	static void strpubw(GbaInstance& instance) {}
	static void ldrpubwl_ImmLSL(GbaInstance& instance) {}
	static void ldrpubwl_ImmLSR(GbaInstance& instance) {}
	static void ldrpubwl_ImmASR(GbaInstance& instance) {}
	static void ldrpubwl_ImmROR(GbaInstance& instance) {}
	static void stri(GbaInstance& instance) {}
	static void ldril_ImmLSL(GbaInstance& instance) {}
	static void ldril_ImmLSR(GbaInstance& instance) {}
	static void ldril_ImmASR(GbaInstance& instance) {}
	static void ldril_ImmROR(GbaInstance& instance) {}
	static void striw(GbaInstance& instance) {}
	static void ldriwl_ImmLSL(GbaInstance& instance) {}
	static void ldriwl_ImmLSR(GbaInstance& instance) {}
	static void ldriwl_ImmASR(GbaInstance& instance) {}
	static void ldriwl_ImmROR(GbaInstance& instance) {}
	static void strib(GbaInstance& instance) {}
	static void ldribl_ImmLSL(GbaInstance& instance) {}
	static void ldribl_ImmLSR(GbaInstance& instance) {}
	static void ldribl_ImmASR(GbaInstance& instance) {}
	static void ldribl_ImmROR(GbaInstance& instance) {}
	static void stribw(GbaInstance& instance) {}
	static void ldribwl_ImmLSL(GbaInstance& instance) {}
	static void ldribwl_ImmLSR(GbaInstance& instance) {}
	static void ldribwl_ImmASR(GbaInstance& instance) {}
	static void ldribwl_ImmROR(GbaInstance& instance) {}
	static void striu(GbaInstance& instance) {}
	static void ldriul_ImmLSL(GbaInstance& instance) {}
	static void ldriul_ImmLSR(GbaInstance& instance) {}
	static void ldriul_ImmASR(GbaInstance& instance) {}
	static void ldriul_ImmROR(GbaInstance& instance) {}
	static void striuw(GbaInstance& instance) {}
	static void ldriuwl_ImmLSL(GbaInstance& instance) {}
	static void ldriuwl_ImmLSR(GbaInstance& instance) {}
	static void ldriuwl_ImmASR(GbaInstance& instance) {}
	static void ldriuwl_ImmROR(GbaInstance& instance) {}
	static void striub(GbaInstance& instance) {}
	static void ldriubl_ImmLSL(GbaInstance& instance) {}
	static void ldriubl_ImmLSR(GbaInstance& instance) {}
	static void ldriubl_ImmASR(GbaInstance& instance) {}
	static void ldriubl_ImmROR(GbaInstance& instance) {}
	static void striubw(GbaInstance& instance) {}
	static void ldriubwl_ImmLSL(GbaInstance& instance) {}
	static void ldriubwl_ImmLSR(GbaInstance& instance) {}
	static void ldriubwl_ImmASR(GbaInstance& instance) {}
	static void ldriubwl_ImmROR(GbaInstance& instance) {}
	static void strip(GbaInstance& instance) {}
	static void ldripl_ImmLSL(GbaInstance& instance) {}
	static void ldripl_ImmLSR(GbaInstance& instance) {}
	static void ldripl_ImmASR(GbaInstance& instance) {}
	static void ldripl_ImmROR(GbaInstance& instance) {}
	static void stripw(GbaInstance& instance) {}
	static void ldripwl_ImmLSL(GbaInstance& instance) {}
	static void ldripwl_ImmLSR(GbaInstance& instance) {}
	static void ldripwl_ImmASR(GbaInstance& instance) {}
	static void ldripwl_ImmROR(GbaInstance& instance) {}
	static void stripb(GbaInstance& instance) {}
	static void ldripbl_ImmLSL(GbaInstance& instance) {}
	static void ldripbl_ImmLSR(GbaInstance& instance) {}
	static void ldripbl_ImmASR(GbaInstance& instance) {}
	static void ldripbl_ImmROR(GbaInstance& instance) {}
	static void stripbw(GbaInstance& instance) {}
	static void ldripbwl_ImmLSL(GbaInstance& instance) {}
	static void ldripbwl_ImmLSR(GbaInstance& instance) {}
	static void ldripbwl_ImmASR(GbaInstance& instance) {}
	static void ldripbwl_ImmROR(GbaInstance& instance) {}
	static void stripu(GbaInstance& instance) {}
	static void ldripul_ImmLSL(GbaInstance& instance) {}
	static void ldripul_ImmLSR(GbaInstance& instance) {}
	static void ldripul_ImmASR(GbaInstance& instance) {}
	static void ldripul_ImmROR(GbaInstance& instance) {}
	static void stripuw(GbaInstance& instance) {}
	static void ldripuwl_ImmLSL(GbaInstance& instance) {}
	static void ldripuwl_ImmLSR(GbaInstance& instance) {}
	static void ldripuwl_ImmASR(GbaInstance& instance) {}
	static void ldripuwl_ImmROR(GbaInstance& instance) {}
	static void stripub(GbaInstance& instance) {}
	static void ldripubl_ImmLSL(GbaInstance& instance) {}
	static void ldripubl_ImmLSR(GbaInstance& instance) {}
	static void ldripubl_ImmASR(GbaInstance& instance) {}
	static void ldripubl_ImmROR(GbaInstance& instance) {}
	static void stripubw(GbaInstance& instance) {}
	static void ldripubwl_ImmLSL(GbaInstance& instance) {}
	static void ldripubwl_ImmLSR(GbaInstance& instance) {}
	static void ldripubwl_ImmASR(GbaInstance& instance) {}
	static void ldripubwl_ImmROR(GbaInstance& instance) {}
} // gg_core::gg_cpu
