namespace gg_core {
	void and_shtLSL(GbaInstance& instance) {}
	void and_shtRsLSL(GbaInstance& instance) {}
	void and_shtLSR(GbaInstance& instance) {}
	void and_shtRsLSR(GbaInstance& instance) {}
	void and_shtASR(GbaInstance& instance) {}
	void and_shtRsASR(GbaInstance& instance) {}
	void and_shtROR(GbaInstance& instance) {}
	void and_shtRsROR(GbaInstance& instance) {}
	void ands_shtLSL(GbaInstance& instance) {}
	void ands_shtRsLSL(GbaInstance& instance) {}
	void ands_shtLSR(GbaInstance& instance) {}
	void ands_shtRsLSR(GbaInstance& instance) {}
	void ands_shtASR(GbaInstance& instance) {}
	void ands_shtRsASR(GbaInstance& instance) {}
	void ands_shtROR(GbaInstance& instance) {}
	void ands_shtRsROR(GbaInstance& instance) {}
	void eor_shtLSL(GbaInstance& instance) {}
	void eor_shtRsLSL(GbaInstance& instance) {}
	void eor_shtLSR(GbaInstance& instance) {}
	void eor_shtRsLSR(GbaInstance& instance) {}
	void eor_shtASR(GbaInstance& instance) {}
	void eor_shtRsASR(GbaInstance& instance) {}
	void eor_shtROR(GbaInstance& instance) {}
	void eor_shtRsROR(GbaInstance& instance) {}
	void eors_shtLSL(GbaInstance& instance) {}
	void eors_shtRsLSL(GbaInstance& instance) {}
	void eors_shtLSR(GbaInstance& instance) {}
	void eors_shtRsLSR(GbaInstance& instance) {}
	void eors_shtASR(GbaInstance& instance) {}
	void eors_shtRsASR(GbaInstance& instance) {}
	void eors_shtROR(GbaInstance& instance) {}
	void eors_shtRsROR(GbaInstance& instance) {}
	void sub_shtLSL(GbaInstance& instance) {}
	void sub_shtRsLSL(GbaInstance& instance) {}
	void sub_shtLSR(GbaInstance& instance) {}
	void sub_shtRsLSR(GbaInstance& instance) {}
	void sub_shtASR(GbaInstance& instance) {}
	void sub_shtRsASR(GbaInstance& instance) {}
	void sub_shtROR(GbaInstance& instance) {}
	void sub_shtRsROR(GbaInstance& instance) {}
	void subs_shtLSL(GbaInstance& instance) {}
	void subs_shtRsLSL(GbaInstance& instance) {}
	void subs_shtLSR(GbaInstance& instance) {}
	void subs_shtRsLSR(GbaInstance& instance) {}
	void subs_shtASR(GbaInstance& instance) {}
	void subs_shtRsASR(GbaInstance& instance) {}
	void subs_shtROR(GbaInstance& instance) {}
	void subs_shtRsROR(GbaInstance& instance) {}
	void rsb_shtLSL(GbaInstance& instance) {}
	void rsb_shtRsLSL(GbaInstance& instance) {}
	void rsb_shtLSR(GbaInstance& instance) {}
	void rsb_shtRsLSR(GbaInstance& instance) {}
	void rsb_shtASR(GbaInstance& instance) {}
	void rsb_shtRsASR(GbaInstance& instance) {}
	void rsb_shtROR(GbaInstance& instance) {}
	void rsb_shtRsROR(GbaInstance& instance) {}
	void rsbs_shtLSL(GbaInstance& instance) {}
	void rsbs_shtRsLSL(GbaInstance& instance) {}
	void rsbs_shtLSR(GbaInstance& instance) {}
	void rsbs_shtRsLSR(GbaInstance& instance) {}
	void rsbs_shtASR(GbaInstance& instance) {}
	void rsbs_shtRsASR(GbaInstance& instance) {}
	void rsbs_shtROR(GbaInstance& instance) {}
	void rsbs_shtRsROR(GbaInstance& instance) {}
	void add_shtLSL(GbaInstance& instance) {}
	void add_shtRsLSL(GbaInstance& instance) {}
	void add_shtLSR(GbaInstance& instance) {}
	void add_shtRsLSR(GbaInstance& instance) {}
	void add_shtASR(GbaInstance& instance) {}
	void add_shtRsASR(GbaInstance& instance) {}
	void add_shtROR(GbaInstance& instance) {}
	void add_shtRsROR(GbaInstance& instance) {}
	void adds_shtLSL(GbaInstance& instance) {}
	void adds_shtRsLSL(GbaInstance& instance) {}
	void adds_shtLSR(GbaInstance& instance) {}
	void adds_shtRsLSR(GbaInstance& instance) {}
	void adds_shtASR(GbaInstance& instance) {}
	void adds_shtRsASR(GbaInstance& instance) {}
	void adds_shtROR(GbaInstance& instance) {}
	void adds_shtRsROR(GbaInstance& instance) {}
	void adc_shtLSL(GbaInstance& instance) {}
	void adc_shtRsLSL(GbaInstance& instance) {}
	void adc_shtLSR(GbaInstance& instance) {}
	void adc_shtRsLSR(GbaInstance& instance) {}
	void adc_shtASR(GbaInstance& instance) {}
	void adc_shtRsASR(GbaInstance& instance) {}
	void adc_shtROR(GbaInstance& instance) {}
	void adc_shtRsROR(GbaInstance& instance) {}
	void adcs_shtLSL(GbaInstance& instance) {}
	void adcs_shtRsLSL(GbaInstance& instance) {}
	void adcs_shtLSR(GbaInstance& instance) {}
	void adcs_shtRsLSR(GbaInstance& instance) {}
	void adcs_shtASR(GbaInstance& instance) {}
	void adcs_shtRsASR(GbaInstance& instance) {}
	void adcs_shtROR(GbaInstance& instance) {}
	void adcs_shtRsROR(GbaInstance& instance) {}
	void sbc_shtLSL(GbaInstance& instance) {}
	void sbc_shtRsLSL(GbaInstance& instance) {}
	void sbc_shtLSR(GbaInstance& instance) {}
	void sbc_shtRsLSR(GbaInstance& instance) {}
	void sbc_shtASR(GbaInstance& instance) {}
	void sbc_shtRsASR(GbaInstance& instance) {}
	void sbc_shtROR(GbaInstance& instance) {}
	void sbc_shtRsROR(GbaInstance& instance) {}
	void sbcs_shtLSL(GbaInstance& instance) {}
	void sbcs_shtRsLSL(GbaInstance& instance) {}
	void sbcs_shtLSR(GbaInstance& instance) {}
	void sbcs_shtRsLSR(GbaInstance& instance) {}
	void sbcs_shtASR(GbaInstance& instance) {}
	void sbcs_shtRsASR(GbaInstance& instance) {}
	void sbcs_shtROR(GbaInstance& instance) {}
	void sbcs_shtRsROR(GbaInstance& instance) {}
	void rsc_shtLSL(GbaInstance& instance) {}
	void rsc_shtRsLSL(GbaInstance& instance) {}
	void rsc_shtLSR(GbaInstance& instance) {}
	void rsc_shtRsLSR(GbaInstance& instance) {}
	void rsc_shtASR(GbaInstance& instance) {}
	void rsc_shtRsASR(GbaInstance& instance) {}
	void rsc_shtROR(GbaInstance& instance) {}
	void rsc_shtRsROR(GbaInstance& instance) {}
	void rscs_shtLSL(GbaInstance& instance) {}
	void rscs_shtRsLSL(GbaInstance& instance) {}
	void rscs_shtLSR(GbaInstance& instance) {}
	void rscs_shtRsLSR(GbaInstance& instance) {}
	void rscs_shtASR(GbaInstance& instance) {}
	void rscs_shtRsASR(GbaInstance& instance) {}
	void rscs_shtROR(GbaInstance& instance) {}
	void rscs_shtRsROR(GbaInstance& instance) {}
	void tsts_shtLSL(GbaInstance& instance) {}
	void tsts_shtRsLSL(GbaInstance& instance) {}
	void tsts_shtLSR(GbaInstance& instance) {}
	void tsts_shtRsLSR(GbaInstance& instance) {}
	void tsts_shtASR(GbaInstance& instance) {}
	void tsts_shtRsASR(GbaInstance& instance) {}
	void tsts_shtROR(GbaInstance& instance) {}
	void tsts_shtRsROR(GbaInstance& instance) {}
	void teqs_shtLSL(GbaInstance& instance) {}
	void teqs_shtRsLSL(GbaInstance& instance) {}
	void teqs_shtLSR(GbaInstance& instance) {}
	void teqs_shtRsLSR(GbaInstance& instance) {}
	void teqs_shtASR(GbaInstance& instance) {}
	void teqs_shtRsASR(GbaInstance& instance) {}
	void teqs_shtROR(GbaInstance& instance) {}
	void teqs_shtRsROR(GbaInstance& instance) {}
	void cmps_shtLSL(GbaInstance& instance) {}
	void cmps_shtRsLSL(GbaInstance& instance) {}
	void cmps_shtLSR(GbaInstance& instance) {}
	void cmps_shtRsLSR(GbaInstance& instance) {}
	void cmps_shtASR(GbaInstance& instance) {}
	void cmps_shtRsASR(GbaInstance& instance) {}
	void cmps_shtROR(GbaInstance& instance) {}
	void cmps_shtRsROR(GbaInstance& instance) {}
	void cmns_shtLSL(GbaInstance& instance) {}
	void cmns_shtRsLSL(GbaInstance& instance) {}
	void cmns_shtLSR(GbaInstance& instance) {}
	void cmns_shtRsLSR(GbaInstance& instance) {}
	void cmns_shtASR(GbaInstance& instance) {}
	void cmns_shtRsASR(GbaInstance& instance) {}
	void cmns_shtROR(GbaInstance& instance) {}
	void cmns_shtRsROR(GbaInstance& instance) {}
	void orr_shtLSL(GbaInstance& instance) {}
	void orr_shtRsLSL(GbaInstance& instance) {}
	void orr_shtLSR(GbaInstance& instance) {}
	void orr_shtRsLSR(GbaInstance& instance) {}
	void orr_shtASR(GbaInstance& instance) {}
	void orr_shtRsASR(GbaInstance& instance) {}
	void orr_shtROR(GbaInstance& instance) {}
	void orr_shtRsROR(GbaInstance& instance) {}
	void orrs_shtLSL(GbaInstance& instance) {}
	void orrs_shtRsLSL(GbaInstance& instance) {}
	void orrs_shtLSR(GbaInstance& instance) {}
	void orrs_shtRsLSR(GbaInstance& instance) {}
	void orrs_shtASR(GbaInstance& instance) {}
	void orrs_shtRsASR(GbaInstance& instance) {}
	void orrs_shtROR(GbaInstance& instance) {}
	void orrs_shtRsROR(GbaInstance& instance) {}
	void mov_shtLSL(GbaInstance& instance) {}
	void mov_shtRsLSL(GbaInstance& instance) {}
	void mov_shtLSR(GbaInstance& instance) {}
	void mov_shtRsLSR(GbaInstance& instance) {}
	void mov_shtASR(GbaInstance& instance) {}
	void mov_shtRsASR(GbaInstance& instance) {}
	void mov_shtROR(GbaInstance& instance) {}
	void mov_shtRsROR(GbaInstance& instance) {}
	void movs_shtLSL(GbaInstance& instance) {}
	void movs_shtRsLSL(GbaInstance& instance) {}
	void movs_shtLSR(GbaInstance& instance) {}
	void movs_shtRsLSR(GbaInstance& instance) {}
	void movs_shtASR(GbaInstance& instance) {}
	void movs_shtRsASR(GbaInstance& instance) {}
	void movs_shtROR(GbaInstance& instance) {}
	void movs_shtRsROR(GbaInstance& instance) {}
	void bic_shtLSL(GbaInstance& instance) {}
	void bic_shtRsLSL(GbaInstance& instance) {}
	void bic_shtLSR(GbaInstance& instance) {}
	void bic_shtRsLSR(GbaInstance& instance) {}
	void bic_shtASR(GbaInstance& instance) {}
	void bic_shtRsASR(GbaInstance& instance) {}
	void bic_shtROR(GbaInstance& instance) {}
	void bic_shtRsROR(GbaInstance& instance) {}
	void bics_shtLSL(GbaInstance& instance) {}
	void bics_shtRsLSL(GbaInstance& instance) {}
	void bics_shtLSR(GbaInstance& instance) {}
	void bics_shtRsLSR(GbaInstance& instance) {}
	void bics_shtASR(GbaInstance& instance) {}
	void bics_shtRsASR(GbaInstance& instance) {}
	void bics_shtROR(GbaInstance& instance) {}
	void bics_shtRsROR(GbaInstance& instance) {}
	void mvn_shtLSL(GbaInstance& instance) {}
	void mvn_shtRsLSL(GbaInstance& instance) {}
	void mvn_shtLSR(GbaInstance& instance) {}
	void mvn_shtRsLSR(GbaInstance& instance) {}
	void mvn_shtASR(GbaInstance& instance) {}
	void mvn_shtRsASR(GbaInstance& instance) {}
	void mvn_shtROR(GbaInstance& instance) {}
	void mvn_shtRsROR(GbaInstance& instance) {}
	void mvns_shtLSL(GbaInstance& instance) {}
	void mvns_shtRsLSL(GbaInstance& instance) {}
	void mvns_shtLSR(GbaInstance& instance) {}
	void mvns_shtRsLSR(GbaInstance& instance) {}
	void mvns_shtASR(GbaInstance& instance) {}
	void mvns_shtRsASR(GbaInstance& instance) {}
	void mvns_shtROR(GbaInstance& instance) {}
	void mvns_shtRsROR(GbaInstance& instance) {}
	void andi(GbaInstance& instance) {}
	void andsi(GbaInstance& instance) {}
	void eori(GbaInstance& instance) {}
	void eorsi(GbaInstance& instance) {}
	void subi(GbaInstance& instance) {}
	void subsi(GbaInstance& instance) {}
	void rsbi(GbaInstance& instance) {}
	void rsbsi(GbaInstance& instance) {}
	void addi(GbaInstance& instance) {}
	void addsi(GbaInstance& instance) {}
	void adci(GbaInstance& instance) {}
	void adcsi(GbaInstance& instance) {}
	void sbci(GbaInstance& instance) {}
	void sbcsi(GbaInstance& instance) {}
	void rsci(GbaInstance& instance) {}
	void rscsi(GbaInstance& instance) {}
	void tstsi(GbaInstance& instance) {}
	void teqsi(GbaInstance& instance) {}
	void cmpsi(GbaInstance& instance) {}
	void cmnsi(GbaInstance& instance) {}
	void orri(GbaInstance& instance) {}
	void orrsi(GbaInstance& instance) {}
	void movi(GbaInstance& instance) {}
	void movsi(GbaInstance& instance) {}
	void bici(GbaInstance& instance) {}
	void bicsi(GbaInstance& instance) {}
	void mvni(GbaInstance& instance) {}
	void mvnsi(GbaInstance& instance) {}
} // gg_core
