namespace gg_core {
	void strh_RmOffset(GbaInstance& instance) {}
	void ldrlh_RmOffset(GbaInstance& instance) {}
	void ldrl(GbaInstance& instance) {}
	void ldrlsh_RmOffset(GbaInstance& instance) {}
	void strh_immOffset(GbaInstance& instance) {}
	void ldrlh_immOffset(GbaInstance& instance) {}
	void ldrbl(GbaInstance& instance) {}
	void ldrlsh_immOffset(GbaInstance& instance) {}
	void struh_RmOffset(GbaInstance& instance) {}
	void ldrulh_RmOffset(GbaInstance& instance) {}
	void ldrul(GbaInstance& instance) {}
	void ldrulsh_RmOffset(GbaInstance& instance) {}
	void struh_immOffset(GbaInstance& instance) {}
	void ldrulh_immOffset(GbaInstance& instance) {}
	void ldrubl(GbaInstance& instance) {}
	void ldrulsh_immOffset(GbaInstance& instance) {}
	void strph_RmOffset(GbaInstance& instance) {}
	void ldrplh_RmOffset(GbaInstance& instance) {}
	void ldrpl(GbaInstance& instance) {}
	void ldrplsh_RmOffset(GbaInstance& instance) {}
	void strpwh_RmOffset(GbaInstance& instance) {}
	void ldrpwlh_RmOffset(GbaInstance& instance) {}
	void ldrpwl(GbaInstance& instance) {}
	void ldrpwlsh_RmOffset(GbaInstance& instance) {}
	void strph_immOffset(GbaInstance& instance) {}
	void ldrplh_immOffset(GbaInstance& instance) {}
	void ldrpbl(GbaInstance& instance) {}
	void ldrplsh_immOffset(GbaInstance& instance) {}
	void strpwh_immOffset(GbaInstance& instance) {}
	void ldrpwlh_immOffset(GbaInstance& instance) {}
	void ldrpbwl(GbaInstance& instance) {}
	void ldrpwlsh_immOffset(GbaInstance& instance) {}
	void strpuh_RmOffset(GbaInstance& instance) {}
	void ldrpulh_RmOffset(GbaInstance& instance) {}
	void ldrpul(GbaInstance& instance) {}
	void ldrpulsh_RmOffset(GbaInstance& instance) {}
	void strpuwh_RmOffset(GbaInstance& instance) {}
	void ldrpuwlh_RmOffset(GbaInstance& instance) {}
	void ldrpuwl(GbaInstance& instance) {}
	void ldrpuwlsh_RmOffset(GbaInstance& instance) {}
	void strpuh_immOffset(GbaInstance& instance) {}
	void ldrpulh_immOffset(GbaInstance& instance) {}
	void ldrpubl(GbaInstance& instance) {}
	void ldrpulsh_immOffset(GbaInstance& instance) {}
	void strpuwh_immOffset(GbaInstance& instance) {}
	void ldrpuwlh_immOffset(GbaInstance& instance) {}
	void ldrpubwl(GbaInstance& instance) {}
	void ldrpuwlsh_immOffset(GbaInstance& instance) {}
	void str(GbaInstance& instance) {}
	void strw(GbaInstance& instance) {}
	void ldrwl(GbaInstance& instance) {}
	void strb(GbaInstance& instance) {}
	void strbw(GbaInstance& instance) {}
	void ldrbwl(GbaInstance& instance) {}
	void stru(GbaInstance& instance) {}
	void struw(GbaInstance& instance) {}
	void ldruwl(GbaInstance& instance) {}
	void strub(GbaInstance& instance) {}
	void strubw(GbaInstance& instance) {}
	void ldrubwl(GbaInstance& instance) {}
	void strp(GbaInstance& instance) {}
	void strpw(GbaInstance& instance) {}
	void strpb(GbaInstance& instance) {}
	void strpbw(GbaInstance& instance) {}
	void strpu(GbaInstance& instance) {}
	void strpuw(GbaInstance& instance) {}
	void strpub(GbaInstance& instance) {}
	void strpubw(GbaInstance& instance) {}
	void stri(GbaInstance& instance) {}
	void ldril(GbaInstance& instance) {}
	void striw(GbaInstance& instance) {}
	void ldriwl(GbaInstance& instance) {}
	void strib(GbaInstance& instance) {}
	void ldribl(GbaInstance& instance) {}
	void stribw(GbaInstance& instance) {}
	void ldribwl(GbaInstance& instance) {}
	void striu(GbaInstance& instance) {}
	void ldriul(GbaInstance& instance) {}
	void striuw(GbaInstance& instance) {}
	void ldriuwl(GbaInstance& instance) {}
	void striub(GbaInstance& instance) {}
	void ldriubl(GbaInstance& instance) {}
	void striubw(GbaInstance& instance) {}
	void ldriubwl(GbaInstance& instance) {}
	void strip(GbaInstance& instance) {}
	void ldripl(GbaInstance& instance) {}
	void stripw(GbaInstance& instance) {}
	void ldripwl(GbaInstance& instance) {}
	void stripb(GbaInstance& instance) {}
	void ldripbl(GbaInstance& instance) {}
	void stripbw(GbaInstance& instance) {}
	void ldripbwl(GbaInstance& instance) {}
	void stripu(GbaInstance& instance) {}
	void ldripul(GbaInstance& instance) {}
	void stripuw(GbaInstance& instance) {}
	void ldripuwl(GbaInstance& instance) {}
	void stripub(GbaInstance& instance) {}
	void ldripubl(GbaInstance& instance) {}
	void stripubw(GbaInstance& instance) {}
	void ldripubwl(GbaInstance& instance) {}
} // gg_core
